/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RepairRouteImport } from './routes/repair'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsGamingRouteImport } from './routes/products.gaming'
import { Route as ProductsCustomPcRouteImport } from './routes/products.custom-pc'
import { Route as ProductsBusinessRouteImport } from './routes/products.business'
import { Route as ProductsAccessoriesRouteImport } from './routes/products.accessories'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRoute = RepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsGamingRoute = ProductsGamingRouteImport.update({
  id: '/gaming',
  path: '/gaming',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCustomPcRoute = ProductsCustomPcRouteImport.update({
  id: '/custom-pc',
  path: '/custom-pc',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsBusinessRoute = ProductsBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsAccessoriesRoute = ProductsAccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/products': typeof ProductsRouteWithChildren
  '/repair': typeof RepairRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/products/accessories': typeof ProductsAccessoriesRoute
  '/products/business': typeof ProductsBusinessRoute
  '/products/custom-pc': typeof ProductsCustomPcRoute
  '/products/gaming': typeof ProductsGamingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/products': typeof ProductsRouteWithChildren
  '/repair': typeof RepairRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/products/accessories': typeof ProductsAccessoriesRoute
  '/products/business': typeof ProductsBusinessRoute
  '/products/custom-pc': typeof ProductsCustomPcRoute
  '/products/gaming': typeof ProductsGamingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/products': typeof ProductsRouteWithChildren
  '/repair': typeof RepairRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/products/accessories': typeof ProductsAccessoriesRoute
  '/products/business': typeof ProductsBusinessRoute
  '/products/custom-pc': typeof ProductsCustomPcRoute
  '/products/gaming': typeof ProductsGamingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/products'
    | '/repair'
    | '/reviews'
    | '/services'
    | '/products/accessories'
    | '/products/business'
    | '/products/custom-pc'
    | '/products/gaming'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/products'
    | '/repair'
    | '/reviews'
    | '/services'
    | '/products/accessories'
    | '/products/business'
    | '/products/custom-pc'
    | '/products/gaming'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/products'
    | '/repair'
    | '/reviews'
    | '/services'
    | '/products/accessories'
    | '/products/business'
    | '/products/custom-pc'
    | '/products/gaming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  RepairRoute: typeof RepairRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/gaming': {
      id: '/products/gaming'
      path: '/gaming'
      fullPath: '/products/gaming'
      preLoaderRoute: typeof ProductsGamingRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/custom-pc': {
      id: '/products/custom-pc'
      path: '/custom-pc'
      fullPath: '/products/custom-pc'
      preLoaderRoute: typeof ProductsCustomPcRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/business': {
      id: '/products/business'
      path: '/business'
      fullPath: '/products/business'
      preLoaderRoute: typeof ProductsBusinessRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/accessories': {
      id: '/products/accessories'
      path: '/accessories'
      fullPath: '/products/accessories'
      preLoaderRoute: typeof ProductsAccessoriesRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsAccessoriesRoute: typeof ProductsAccessoriesRoute
  ProductsBusinessRoute: typeof ProductsBusinessRoute
  ProductsCustomPcRoute: typeof ProductsCustomPcRoute
  ProductsGamingRoute: typeof ProductsGamingRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsAccessoriesRoute: ProductsAccessoriesRoute,
  ProductsBusinessRoute: ProductsBusinessRoute,
  ProductsCustomPcRoute: ProductsCustomPcRoute,
  ProductsGamingRoute: ProductsGamingRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ProductsRoute: ProductsRouteWithChildren,
  RepairRoute: RepairRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
